services:

    db_mysql:
        image: mysql
        #restart:always
        ports:
            - "3301:3306"
        volumes:
            - ./my.cnf:/etc/my.cnf
            - ./db_mysql_volume:/var/lib/mysql
        env_file:
            - .env
